'use strict';
const $=id=>document.getElementById(id);
let files=[],pending=null,lastRoutes=[],ready=false,busy=false,firstUse=true,saveChain=Promise.resolve(),pollTimer;
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('pointer-web',1);req.onupgradeneeded=()=>req.result.createObjectStore('draft');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
async function store(value){const durable={...value,files:await Promise.all(value.files.map(async file=>({name:file.name,type:file.type,lastModified:file.lastModified,buffer:await file.arrayBuffer()})))};const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(durable,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function load(){const db=await dbPromise;const value=await new Promise((resolve,reject)=>{const req=db.transaction('draft').objectStore('draft').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(value)value.files=(value.files||[]).map(file=>file instanceof File?file:new File([file.buffer],file.name,{type:file.type,lastModified:file.lastModified}));return value;}
function snapshot(){return {text:$('text').value,instruction:$('instruction').value,url:$('url').value,target:$('target').value,files:[...files],pending,routes:[...lastRoutes]};}
function save(){const value=snapshot();saveChain=saveChain.catch(()=>{}).then(()=>store(value));return saveChain;}
function status(text){$('status').textContent=text;}
const hosted=location.hostname==='samingz.github.io';
let privateKey=localStorage.getItem('pointer-device-key')||'';
async function api(path,data){const control=new AbortController(),timer=setTimeout(()=>control.abort(),60000);try{let base='';if(hosted){const config=await fetch('./endpoint.json?t='+Date.now(),{cache:'no-store',signal:control.signal}).then(r=>r.json());const endpoint=new URL(config.endpoint);if(endpoint.protocol!=='https:'||!endpoint.hostname.endsWith('.trycloudflare.com'))throw new Error('Invalid relay address');base=endpoint.origin;}const headers=data?{'Content-Type':'application/json'}:{};if(hosted&&privateKey)headers.Authorization='Bearer '+privateKey;const response=await fetch(base+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined,signal:control.signal,credentials:hosted?'omit':'same-origin'});const result=await response.json();if(!response.ok){const error=new Error(result.error||'Connection failed');error.httpStatus=response.status;throw error;}return result;}finally{clearTimeout(timer);}}
function menu(rows,chosen){lastRoutes=rows;$('target').replaceChildren(new Option('Choose a conversation',''),...rows.map(r=>new Option(r.title,r.link)));$('target').value=rows.some(r=>r.link===chosen)?chosen:'';if(!chosen&&firstUse&&rows.length)$('target').value=rows[0].link;if(rows.length)firstUse=false;}
async function sync(){const chosen=$('target').value;$('sync').disabled=true;status('Refreshing conversations…');try{const result=await api('/api/routes');menu(result.routes,chosen);ready=true;await save();status(chosen&&!$('target').value?'Previous conversation was removed. Choose another.':'Conversation list refreshed.');}catch(error){status(error.message+' Existing draft and list retained.');}finally{$('sync').disabled=false;}}
function renderFiles(){$('attachments').replaceChildren();files.forEach((file,index)=>{const row=document.createElement('div');row.className='file';if(file.type.startsWith('image/')){const img=document.createElement('img');const url=URL.createObjectURL(file);img.src=url;img.onload=()=>URL.revokeObjectURL(url);row.append(img);}const name=document.createElement('span');name.textContent=file.name;const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Remove '+file.name);remove.onclick=()=>{if(pending)return;files.splice(index,1);renderFiles();save();};remove.disabled=!!pending;row.append(name,remove);$('attachments').append(row);});}
function lock(){['text','instruction','url','target','files','clear'].forEach(id=>$(id).disabled=!!pending);$('send').disabled=!!pending;$('check').hidden=!pending;renderFiles();}
function base64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
async function receipt(result){status((result.task_id?'['+result.task_id+'] ':'')+result.detail);if(result.status==='accepted'){pending=null;files=[];$('text').value='';$('instruction').value='';$('url').value='';$('files').value='';lock();await save();}else if(result.status==='not_sent'){pending=null;lock();await save();}else if(result.status!=='uncertain'){clearTimeout(pollTimer);pollTimer=setTimeout(check,2500);}}
async function check(){if(!pending||busy)return;busy=true;try{let result;try{result=await api('/api/receipt/'+pending.id);}catch(error){if(error.httpStatus!==404)throw error;status('Recovering the same saved request…');result=await api('/api/send',pending);}await receipt(result);}catch(error){status(error.message+' Draft retained; no new request created.');}finally{busy=false;}}
async function send(){if(busy)return;if(pending)return check();if(!ready||!$('target').value){status('Sync and choose a conversation first.');return;}if(!$('instruction').value.trim()){status('Enter an instruction.');$('instruction').focus();return;}busy=true;$('send').disabled=true;let dispatched=false;try{const content=snapshot();pending={id:crypto.randomUUID(),target:content.target,text:content.text,instruction:content.instruction,url:content.url,files:await Promise.all(content.files.map(async f=>({name:f.name,data:await base64(f)})))};await save();lock();status('Sending…');dispatched=true;await receipt(await api('/api/send',pending));}catch(error){if(!dispatched||[400,401,403,413,415].includes(error.httpStatus)){pending=null;await save().catch(()=>{});}status(error.message+' Your draft is retained.'+(pending?' Check delivery before retrying.':''));lock();}finally{busy=false;$('send').disabled=!!pending;}}
$('files').onchange=async()=>{try{const additions=Array.from($('files').files);if(files.length+additions.length>3||additions.some(f=>!f.size||f.size>15000000)){status('Up to three files, each between 1 byte and 15 MB.');$('files').value='';return;}const copied=await Promise.all(additions.map(async file=>new File([await file.arrayBuffer()],file.name,{type:file.type,lastModified:file.lastModified})));files.push(...copied);$('files').value='';renderFiles();await save();status('Draft saved on this device.');}catch(error){status('Attachment draft could not be saved ('+error.name+'). Keep this page open.');}};
['text','instruction','url','target'].forEach(id=>$(id).addEventListener('input',()=>save().catch(()=>status('Draft storage unavailable. Keep this page open.'))));
$('sync').onclick=sync;$('send').onclick=send;$('check').onclick=check;$('clear').onclick=async()=>{if(pending)return;files=[];['text','instruction','url','files'].forEach(id=>$(id).value='');renderFiles();await save();status('Draft cleared.');};
(async()=>{try{const draft=await load();if(draft){firstUse=false;['text','instruction','url'].forEach(id=>$(id).value=draft[id]||'');files=draft.files||[];pending=draft.pending||null;menu(draft.routes||[],draft.target||'');}lock();const key=new URLSearchParams(location.hash.slice(1)).get('key');if(key){if(hosted){privateKey=key;localStorage.setItem('pointer-device-key',key);}await api('/api/login',{key});if(!hosted)history.replaceState(null,'',location.pathname);}await sync();if(pending)await check();}catch(error){status(error.message+' Saved draft retained on this device.');}})();
